### ISSUE TITLE
KeyError in tokenTags[tokenName]

### ISSUE THREAD

**Issue by will-moore** [MicronOxford/webtagging#29]
From https://www.openmicroscopy.org/qa2/qa/feedback/11092/
Web Bug 5.1.1-ice35-b43

"trying to use auto tag, a newly created tag ("20X") didn't appear in the tags dropdown list for other columns after applying and refreshing"

```
Traceback (most recent call last):
File "/home/demo/OMERO-CURRENT/lib/python/django/core/handlers/base.py", line 114, in get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/demo/OMERO-CURRENT/lib/python/omeroweb/decorators.py", line 471, in wrapped
retval = f(request, *args, **kwargs)
File "/home/demo/OMERO-CURRENT/lib/python/omeroweb/decorators.py", line 521, in wrapper
context = f(request, *args, **kwargs)
File "/home/demo/web-extensions/autotag/views.py", line 742, in process_update
tagId = tokenTags[tokenName]
KeyError: u'20X '
path:/autotag/auto_tag/processUpdate/,
```

**Comment by dpwrussell** [comment]
Can you elaborate on this at all @will-moore ?

"didn't appear in the tags dropdown for **other columns** after applying and refreshing" might explain this issue. The dropdowns for each column only show the tags which have been auto-matched to a token or explicitly added to the dropdown by selecting it through the `New/Existing Tag` dialog.

Also, a design decision was made that no more than one column can simultaneously match a tag because this would cause potential conflicts in what was to be applied.

**Comment by will-moore** [comment]
I can't add anything to this - it was a bug submitted to QA from mit.edu (see link above).

**Comment by dpwrussell** [comment]
I'm going to close this as I can't confirm. If it reoccurs, please reopen.

**Comment by pwalczysko** [comment]
@dpwrussell : Could not be the problem here the ``....refreshing`` part ? The issue with the ``Refresh`` button in Webtagging is that is does not refresh at all, instead it somehow gets back to Default or some previous original state....
