### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by carandraug** [MicronOxford/webtagging#69]
With python 2 support ending, OMERO is moving to Python 3 (see [OMERO / Python 3 Rollout Plan](https://forum.image.sc/t/omero-python-3-rollout-plan/31278)). Not sure how much would work would be to port these to Python 3 but in addition to the Python2->3 changes, the OMERO python library also come with some API changes although I'm not sure if those are anywhere that matter for these.

**Comment by sbesson** [comment]
A quick update since the `webtagging` app has been part of our testing Web deployment for the last years. As a result of our internal deployments being migrated to Python3/Django 1.11 as well as more stringent checks when starting Web apps (see https://github.com/ome/omero-web/pull/79), we have now disabled the `webtagging` app from our daily CI environment. 

Obviously, let us know if you need more information about the migration path. In terms of code, https://github.com/ome/omero-weberror/pull/20, https://github.com/ome/omero-figure/pull/344, https://github.com/ome/omero-parade/pull/64 and https://github.com/ome/omero-iviewer/pull/285 are the most relevant upgrade PRs for core OME apps and might be the best starting points. From our side, we will be happy to re-enable this app into our CI framework to support the testing of changes restoring compatibility with the OMERO 5.6 environment.

/cc @will-moore @joshmoore @jburel @pwalczysko  @manics @dpwrussell

**Comment by dpwrussell** [comment]
@sbesson Thanks. There should be a new version (#70) in the very near future. Once that PR is complete and merged it would be great to get back into your CI environment.
